plugins {
    // AGP 9 has built-in Kotlin support and registers the `kotlin` extension itself. Applying the
    // standalone org.jetbrains.kotlin.android plugin fails with
    // "Cannot add extension with name 'kotlin'".
    alias(libs.plugins.android.library)
}

android {
    // Namespace deliberately kept as com.bhashabridge.app, NOT renamed to com.learnbridge.engine.
    // MtEngine imports com.bhashabridge.app.Direction, .bench.Metrics, .logDebug and BuildConfig.
    // Renaming means touching ~20 files and regenerating BuildConfig under a new namespace — 20
    // chances to break a working, benchmarked inference engine. The cosmetic mismatch is free.
    namespace = "com.bhashabridge.app"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        minSdk = 24

        // OnnxModels.cacheStamp() uses BuildConfig.VERSION_CODE as part of the key that decides
        // whether the baked .ort model must be regenerated. AGP only generates VERSION_CODE for
        // application modules, not libraries, so it is declared here explicitly rather than editing
        // the engine source.
        //
        // Bump this whenever a graph export or the decode path changes. The other two components of
        // that cache key — the ONNX Runtime version and the source asset's byte length — already
        // cover a re-exported model, so this is the narrow case of "same weights, different code".
        buildConfigField("int", "VERSION_CODE", "1")
    }

    // Load-bearing, not boilerplate: logDebug() compiles itself out of release builds via
    // BuildConfig.DEBUG, and BuildConfig is not generated by default since AGP 8.
    buildFeatures {
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    // ONNX Runtime ships more than one copy of some .so files; without pickFirsts the merge fails on
    // duplicate native libs. Kept here as well as in :app because a library module that is consumed
    // elsewhere should carry its own packaging facts.
    packaging {
        jniLibs {
            pickFirsts += setOf(
                "**/libonnxruntime.so",
                "**/libonnxruntime4j_jni.so",
            )
        }
    }
}

dependencies {
    api(libs.onnxruntime.android)
    api(libs.kotlinx.coroutines.android)

    testImplementation(libs.junit)
}
